site_name: CueMol &mdash; Molecular Visualization Framework
site_url: https://cuemol.github.io/cuemol2_docs/
repo_url: https://github.com/CueMol/cuemol2
theme:
  name: material
  # language: ja
  # features:
  #   - toc.integrate
  #   - navigation.tabs
  logo: assets/images/cuemol2-small-80px.png
  favicon: assets/favicon.ico

plugins:
  - glightbox:
      manual: true
  - i18n:
      fallback_to_default: true
      docs_structure: folder
      languages:
        - locale: ja
          default: true
          name: 日本語
          build: true

        - locale: en
          name: English
          build: true
          nav:
            - Home: index.md
            - Documents: Documents.md
            - Gallery: Gallery.md
            - Updates: Updates.md
            - Environment: Environment.md
            - Download: Download.md
            - Install: Install.md
            - Licence: Licence.md
            #  - Donation: Licence.md
            - Link: Link.md
            
markdown_extensions:
  - pymdownx.tilde
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
      toc_depth: 6

extra:
  alternate:
    - name: 日本語
      link: ja/../
      lang: ja
    - name: English
      link: en/
      lang: en

nav:
  - トップページ: index.md
  - ドキュメント: Documents.md
  - ギャラリー: en/Gallery
  - アップデート: Updates.md
  - 動作環境: 動作環境.md
  - ダウンロード: Download.md
  - インストール: Install.md
  - ライセンス: Licence.md
#   - 寄付: Licence.md
  - リンク: リンク.md

extra_css:
  - stylesheets/extra.css
